<?xml version="1.0" encoding="UTF-8"?>
<robot name="atbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find atbot_description)/urdf/materials.xacro" />
  <!-- Robot constants and properties -->
  <xacro:include filename="$(find atbot_description)/urdf/atbot_properties.xacro" />
  <!-- Inertia matrices -->
  <xacro:include filename="$(find atbot_description)/urdf/macros.xacro" />
  <!-- Gazebo aspects of the robot -->
	<xacro:include filename="$(find atbot_description)/urdf/atbot.gazebo" />

  <!-- Attach LiDAR plugin -->
  <xacro:if value="$(arg lidar_enabled)">
    <xacro:include filename="$(find atbot_description)/urdf/accessories/VLP-16.urdf.xacro"/>
    <VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points" hz="10" samples="1800" gpu="false" min_range="0" max_range="50.0" noise="0.01">
      <origin xyz="$(arg lidar_xyz)" rpy="$(arg lidar_rpy)" />
    </VLP-16>
  </xacro:if>

  <!-- Attach D435 plugin -->
  <!-- <xacro:if value="$(arg d435_enabled)">
    <xacro:include filename="$(find atbot_description)/urdf/accessories/_d435.urdf.xacro" />
    <sensor_d435 parent="base_link">
      <origin xyz="$(arg d435_xyz)" rpy="$(arg d435_rpy)" />
    </sensor_d435>
  </xacro:if> -->


  <!-- base_link -->
  <link name='base_link'>

		<collision> 
			<origin xyz="0 0 ${wheelRadius}" 
					rpy="0 0 0"/> 
			<geometry> 
				<mesh filename="package://atbot_description/meshes/base_link.STL" />
			</geometry> 
		</collision>

		<visual> 
			<origin xyz="0 0 ${wheelRadius}" 
					rpy="0 0 0"/> 
			<geometry>  
				<mesh filename="package://atbot_description/meshes/base_link.STL" />
			</geometry> 
			<!-- <material name="red"/> -->
		</visual>

		<inertial> 
			<origin xyz="0 0 ${wheelRadius}" 
					rpy="0 0 0"/> 
			<mass value="${baseMass}"/> 
			<box_inertia 
				m="${baseMass}" 
				x="${baseLength}" 
				y="${baseWidth}" 
				z="${baseHeight}"/>
		</inertial>

	</link><!-- end of base_link -->


  <!-- caster_wheel -->
  <joint name="caster_joint" type="fixed">
		<parent link="base_link"/>
		<child link="caster_wheel"/>
	</joint>

  <link name="caster_wheel">

		<collision>
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://atbot_description/meshes/caster_wheel.dae" />
	  		</geometry>
		</collision>

		<visual> 
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://atbot_description/meshes/caster_wheel.dae" />
			</geometry>
			<material name="grey" />
		</visual>

		<inertial>
			<origin xyz="${casterOffsetX} 0 ${2*casterRadius}" 
					rpy="0 0 0"/>
			<mass value="${casterMass}"/>
			<sphere_inertia 
				m="${casterMass}" 
				r="${casterRadius}"/>
		</inertial>

	</link><!-- end of caster_wheel -->

  <wheel lr="left" tY="-1"/>
  <wheel lr="right" tY="1"/>

</robot>